// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRHe99llvOMwa_8COU5Jsc9jhjWiG8EXM',
    appId: '1:265296325179:web:6f635284ff49d58581ca1e',
    messagingSenderId: '265296325179',
    projectId: 'wadiah-6225a',
    authDomain: 'wadiah-6225a.firebaseapp.com',
    databaseURL: 'https://wadiah-6225a-default-rtdb.firebaseio.com',
    storageBucket: 'wadiah-6225a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSyUaCx1Ulcq7yyZUe-ahYhEfvnt7E2u4',
    appId: '1:265296325179:android:fd65af4a5a2cadd481ca1e',
    messagingSenderId: '265296325179',
    projectId: 'wadiah-6225a',
    databaseURL: 'https://wadiah-6225a-default-rtdb.firebaseio.com',
    storageBucket: 'wadiah-6225a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWXxe6Vw-JBLay2hub_MW2CQj31SnRO5U',
    appId: '1:265296325179:ios:95c42cfc7a433b8981ca1e',
    messagingSenderId: '265296325179',
    projectId: 'wadiah-6225a',
    databaseURL: 'https://wadiah-6225a-default-rtdb.firebaseio.com',
    storageBucket: 'wadiah-6225a.firebasestorage.app',
    iosClientId: '265296325179-2mua08nche4hbgu3njbmmfumq3dt2oqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.wadiahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWXxe6Vw-JBLay2hub_MW2CQj31SnRO5U',
    appId: '1:265296325179:ios:95c42cfc7a433b8981ca1e',
    messagingSenderId: '265296325179',
    projectId: 'wadiah-6225a',
    databaseURL: 'https://wadiah-6225a-default-rtdb.firebaseio.com',
    storageBucket: 'wadiah-6225a.firebasestorage.app',
    iosClientId: '265296325179-2mua08nche4hbgu3njbmmfumq3dt2oqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.wadiahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRHe99llvOMwa_8COU5Jsc9jhjWiG8EXM',
    appId: '1:265296325179:web:8acda415413919df81ca1e',
    messagingSenderId: '265296325179',
    projectId: 'wadiah-6225a',
    authDomain: 'wadiah-6225a.firebaseapp.com',
    databaseURL: 'https://wadiah-6225a-default-rtdb.firebaseio.com',
    storageBucket: 'wadiah-6225a.firebasestorage.app',
  );

}